name: Run Python Script

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "0 19 * * *"  # Runs at 12:00 PM PST daily (adjust the cron as needed)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


      - name: Run the Python script
        run: |
          python gha_script.py

      - name: Check if results exist
        id: check_results
        run: |
          if [ -f changes.txt ] && [ -s changes.txt ]; then
            echo "results_exist=true" >> $GITHUB_ENV
          else
            echo "results_exist=false" >> $GITHUB_ENV
          fi

      - name: Email results
        if: env.results_exist == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "GitHub Action Results"
          body: "See the attached results from the GitHub Action."
          to: "morganmason0606@gmail.com"
          from: "morganmason0606@gmail.com"
          attachments: changes.txt

      - name: Commit jobs.db if changed
        if: env.results_exist == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add jobs.db
          git commit -m "Update jobs.db"
          git push
